import '../model/model.dart';

abstract class MediaRepository {
  Future<List<EpisodeHistory>> getEpisodeHistories({required String videoId});

  Future<void> saveEpisodeHistory(String videoId, EpisodeHistory history);

  Future<void> savePlayerSettings(PlayerSetting setting);
  Future<PlayerSetting> getPlayerSettings({required String videoId});
}

/// Optional persistence for per-episode intro/outro markers.
///
/// Deliberately NOT part of [MediaRepository]: `implements` demands every
/// member, so adding methods there would break every existing repository.
/// Implement both interfaces to have markers survive restarts; implement only
/// [MediaRepository] and markers still work for the session, they just aren't
/// stored.
///
/// ```dart
/// class MyRepo implements MediaRepository, EpisodeMarkerStore { ... }
/// ```
abstract class EpisodeMarkerStore {
  Future<List<EpisodeMarkers>> getEpisodeMarkers({required String videoId});

  Future<void> saveEpisodeMarkers(String videoId, EpisodeMarkers markers);
}

/// Optional persistence for the perceptual hashes a background sweep produces.
///
/// Intro/outro detection compares one episode against ANOTHER swept episode,
/// so without this the feature only fires when a viewer happens to leave the
/// player open across two episodes — each session starts blind and pays a
/// ~5-minute sweep per episode before it can compare anything. Stored hashes
/// turn every later episode into a one-sweep answer.
///
/// Only the hashes, deliberately — NOT the preview tiles. Hashes are ~4KB per
/// episode against ~2MB of PNG, and the tiles are regenerated by the ordinary
/// background sweep within minutes of playback, so storing them would buy a
/// quota policy and a stale-art problem for something already free.
///
/// [hashes] is an opaque blob owned by the SDK — store and return the bytes
/// unchanged. It is versioned, and a blob this SDK does not recognise is
/// discarded rather than misread.
///
/// Same opt-in shape as [EpisodeMarkerStore]: implement it and detection
/// survives restarts; skip it and everything works exactly as before, just
/// within a single session.
abstract class EpisodeHashStore {
  /// Stored blobs for this video, keyed by episode index. Missing episodes
  /// simply have no entry.
  Future<Map<int, List<int>>> getEpisodeHashes({required String videoId});

  Future<void> saveEpisodeHashes(
    String videoId,
    int episodeIndex,
    List<int> hashes,
  );
}
